FROM honkit/honkit

#RUN apt-get update && apt-get install -y default-jre
#RUN npm install -g gitbook-plugin-uml

RUN npm install -g \
      gitbook-plugin-custom-js-css \
      gitbook-plugin-copy-code-button \
      gitbook-plugin-search-pro-fixed \
      @dogatana/honkit-plugin-page-toc-button \
      @dogatana/honkit-plugin-back-to-top-button
